// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmbEcErOZsPXAPJe3He4vQCOm92DXtJc',
    appId: '1:217931886509:web:17594d19505f7fd83bbb24',
    messagingSenderId: '217931886509',
    projectId: 'apple-ecommerce-0',
    authDomain: 'apple-ecommerce-0.firebaseapp.com',
    storageBucket: 'apple-ecommerce-0.appspot.com',
    measurementId: 'G-KG7L3VREGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6z1uE0KtnWVT8lx1lU-kgezFAEfAz6M',
    appId: '1:217931886509:android:0a150ec7803ac8823bbb24',
    messagingSenderId: '217931886509',
    projectId: 'apple-ecommerce-0',
    storageBucket: 'apple-ecommerce-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpbKsLjBqw-HF6MuaYRezVNpKFx-lEjtA',
    appId: '1:217931886509:ios:5815ef645706a5b23bbb24',
    messagingSenderId: '217931886509',
    projectId: 'apple-ecommerce-0',
    storageBucket: 'apple-ecommerce-0.appspot.com',
    iosBundleId: 'lk.apple.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpbKsLjBqw-HF6MuaYRezVNpKFx-lEjtA',
    appId: '1:217931886509:ios:e581bc55e95235e23bbb24',
    messagingSenderId: '217931886509',
    projectId: 'apple-ecommerce-0',
    storageBucket: 'apple-ecommerce-0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSmbEcErOZsPXAPJe3He4vQCOm92DXtJc',
    appId: '1:217931886509:web:3fc805b5a8322f253bbb24',
    messagingSenderId: '217931886509',
    projectId: 'apple-ecommerce-0',
    authDomain: 'apple-ecommerce-0.firebaseapp.com',
    storageBucket: 'apple-ecommerce-0.appspot.com',
    measurementId: 'G-KKEQCHL4LQ',
  );
}
